{{- if (empty .Values.existingConfigMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fluent-bit.fullname" . }}-config
  labels:
    app: {{ template "fluent-bit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  fluent-bit-service.conf: |-
    [SERVICE]
        Flush        {{ .Values.service.flush }}
        Daemon       Off
        Log_Level    {{ .Values.service.logLevel }}
        Parsers_File parsers.conf
{{- if .Values.parsers.enabled }}
        Parsers_File parsers_custom.conf
{{- end }}
{{- if .Values.metrics.enabled }}
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020
{{- end }}

  fluent-bit-input.conf: |-
{{- if .Values.config.input }}
{{- range .Values.config.input }}
    [INPUT]
        Name                tail
        Path                {{ .path }}
        Parser              {{ .parser }}
        Tag                 kube.*
        Refresh_Interval    5
        Mem_Buf_Limit       5MB
        Skip_Long_Lines     On
{{ end }}
{{- end }}

  fluent-bit-filter.conf: |-
    [FILTER]
        Name                kubernetes
        Match               {{ .Values.filter.kubeTag }}.*
        Kube_Tag_Prefix     {{ .Values.filter.kubeTagPrefix }}
        Kube_URL            {{ .Values.filter.kubeURL }}
        Kube_CA_File        {{ .Values.filter.kubeCAFile }}
        Kube_Token_File     {{ .Values.filter.kubeTokenFile }}
{{- if .Values.filter.mergeJSONLog }}
        Merge_Log           On
{{- end }}

{{- if .Values.filter.mergeLogKey }}
        Merge_Log_Key       {{ .Values.filter.mergeLogKey }}
{{- end }}

{{- if .Values.filter.enableParser }}
        K8S-Logging.Parser  On
{{- end }}
{{- if .Values.filter.enableExclude }}
        K8S-Logging.Exclude On
{{- end }}
{{ .Values.extraEntries.filter | indent 8 }}
{{ .Values.config.filter | indent 4 }}

  fluent-bit-output.conf: |-
{{- if eq .Values.backend.type "es" }}
{{- $backendType := .Values.backend.type -}}
{{- $backendEsHost := .Values.backend.es.host -}}
{{- $backendEsPort := .Values.backend.es.port -}}
{{- $backendEsUser := .Values.backend.es.http_user -}}
{{- $backendEsPassword := .Values.backend.es.http_passwd -}}
{{- $backendEsType := .Values.backend.es.type -}}
{{- $backendEsTimeKey := .Values.backend.es.time_key -}}
{{- $backendEsReplaceDot := .Values.backend.es.replace_dots -}}
{{- if .Values.config.output }}
{{- range .Values.config.output }}
    [OUTPUT]
        Name            {{ $backendType }}
        Match           {{ .match }}
        Host            {{ $backendEsHost }}
        Port            {{ $backendEsPort }}
        HTTP_User       {{ $backendEsUser }}
        HTTP_Passwd     {{ $backendEsPassword }}
        Logstash_Format On
        Retry_Limit     False
        # Type            {{ $backendEsType }}
        Time_Key        {{ $backendEsTimeKey }}
        Replace_Dots    {{ $backendEsReplaceDot }}
        Logstash_Prefix {{ .logstash_Prefix }}
{{ end }}
{{- end }}
{{- end }}

  fluent-bit.conf: |-
{{ .Values.rawConfig | indent 4 }}

  parsers.conf: |-
{{- if .Values.parsers.regex }}
{{- range .Values.parsers.regex }}
    [PARSER]
        Name        {{ .name }}
        Format      regex
        Regex       {{ .regex }}
{{- if .timeKey }}
        Time_Key    {{ .timeKey }}
{{- end }}
{{- if .timeFormat }}
        Time_Format {{ .timeFormat }}
{{- end }}
{{ end }}
{{- end }}
{{- if .Values.parsers.json }}
{{- range .Values.parsers.json }}
    [PARSER]
        Name        {{ .name }}
        Format      json
{{- if .timeKeep }}
        Time_Keep   {{ .timeKeep }}
{{- end }}
{{- if .timeKey }}
        Time_Key    {{ .timeKey }}
{{- end }}
{{- if .timeFormat }}
        Time_Format {{ .timeFormat }}
{{- end }}
{{- if .decodeFieldAs  }}
        Decode_Field_As {{ .decodeFieldAs }} {{ .decodeField | default "log" }}
{{- end}}
{{- if .extraEntries }}
{{ .extraEntries | indent 8 }}
{{- end }}
{{ end }}
{{- end }}
{{- if .Values.parsers.logfmt }}
{{- range .Values.parsers.logfmt }}
    [PARSER]
        Name        {{ .name }}
        Format      logfmt
{{- if .timeKey }}
        Time_Key    {{ .timeKey }}
{{- end }}
{{- if .timeFormat }}
        Time_Format {{ .timeFormat }}
{{- end }}
{{- if .extraEntries }}
{{ .extraEntries | indent 8 }}
{{- end }}
{{ end }}
{{- end }}

{{- end -}}
